theme: jekyll-theme-minimal
title: Qianqian Wang
description: Welcome to my website! Ph.D. Cadidate in Micro-/nano-robotics, Department of Mechanical and Automation Engineering, The Chinese University of Hong Kong. Email: qqwang@mae.cuhk.edu.hk
show_downloads: false
logo: logo.jpg
github:
  is_project_page: false
